---
title: "On The Uncertain Future of Science Communication in the Fediverse"
author: "Nico D'Angelo"
date: "2023-06-22"
slug: "on-the-uncertain-future-of-science-communication-in-the-fediverse"
draft: TRUE
categories: scicomm
tags: Mastodon
---
## Digital Science communication, past and present

Science communication didn't start with social media, or even the internet. Scientists working for government agencies have long given press conferences, testified in public hearings before legislatures, and given lectures and talks open to the public. And scientists were some of the first to make use of the internet.  But, online social media platforms give virtually any member of the public with an internet connection the opportunity to connect with *individual* scientists at virtually all hours of the day. Even university students don't have that kind of access to experts in a given field. 

### On the death of Science Twitter

Beginning with the announcement of Elon Musk's takeover of Twitter (insert date), many scientists who had become active on the platform in years prior became concerned about the future of their professional networks and communities they'd built. Several had great success in establishing a platform to communicate their results, discuss open questions in their fields with a perhaps unprecedented network of colleagues around the world, and (at least in theory) make academic science accessible to the public in a way that really hadn't existed before social media like it.  It was undoubtedly a convenient tool for finding and sharing the newest research in a given field with immediate effect. All a scientist had to do was post a link to a journal or a preprint server, and 100s-1000s of their colleagues would see it within hours to days, no doubt bolstered by Twitter's (in)famous recommendation algorithm.


My field's relationship with Twitter in general, and Musk in particular, has been even more turbulent. On the one hand,  relevant public health  and life scientists (including epidemiologists, virologists, molecular biologists, evolutionary biologists, disease ecologists) clinicians, and health policy researchers all made use of this round-the-clock, global communication tool to our advantage in the face of a global health crisis with no recent precedent. With so much data coming at us from all directions, so many unstable dynamics to watch as carefully as possible, I'm not sure how else we could've kept up with each other. That said, we also had to deal with a threat new to most in Public Health -our climate science friends haven't been so lucky- the seemingly endless onslaughts of the tinfoil hat brigade. Grifters and conspiracy theorists have worked overtime to confuse and disorient, muddying the waters of every aspect of COVID-19 and measures intended to mitigate it, up to and including the virus' very existence and pathogenisis in humans. Then there's the virulent harassment of scientists and Public Health officials, in which the likes of Elon Musk all too eagerly participated.    
It may be worth revisiting the early promise of social media and the internet at-large "democratizing information," and by extension, science. (Refs)

### Maybe we shouldn't miss it too much?

I can personally attest to how helpful "SciTwitter" was. As graduate students we're told that networking is crucial, and that social media is an increasingly important tool in those endeavors. Particularly being in Public Health graduate school *en pleine pandemie*, hearing from experts around the world at all times kept me far better informed than the largely superficial and sometimes dangerously inaccurate coverage in mainstream media. I watched as Bioinformaticians and Molecular Epidemiologists alerted each other to sequence database outages in real-time. New data on the immunology and epidemiology of the ever-rapidly evolving SARS-CoV-2 strains was at my fingertips within days, explained in well written threads by the authors of papers that would've been drowned out among the thousands of preprints and newly published articles in almost every journal. I got to learn about the science of airborne hazard mitigation, from filtration and ventilation to respirator fitting from environmental engineers and industrial hygienists  whom I likely never would have encountered otherwise.

Aside from the ongoing COVID-19 pandemic, I've lost track of how many times I had a programming issue, fired off a quick Tweet with the right hashtag, and gotten better help than StackOverflow has ever offered in a matter of minutes.


Whatever value we once found on the platform, it's important to remember a lesson many of us learned the hard way: An **algorithmic rage machine,** however incidentally helpful it may be, is still a rage machine. Twitter was full of vile bigotry and harassment long before Musk threw open the floodgates for avowed fascists to openly flood the platform. Despite existing for nearly two decades, Twitter never seemed to really address its users' increasingly urgent concerns over moderation of the bile some of its users spewed onto others, often with the algorithm's help in propagation. Mis- and disinformation on all manner of topics ran rampant, with apparently few serious or at least clearly effective mitigation efforts from the company.

## Whither Science Mastodon?

While several science-oriented mastodon instances have been created before and since the so-called "Twitter Migration" to Mastodon and the broader Fediverse, it is clear that the networks many of us in the sciences had spent years building have largely not be reconstituted. Personally, I left a flag on my Twitter account inviting people to migrate to Mastodon with me for months. Some with whom I had important connections did come over within the first few weeks, even helping me navigate the new platform. But as months went on and the "birdsite" became increasingly unstable and hate-filled under Elon's control, most apparently stayed or abandoned social media altogether (the smartest option).  

However, the scattering of scientists across mostly discipline-specific instances runs the risk of making it much more difficult for the majority of people, who don't necessarily know which scientists to look for and where to find them, to get access to science they need or want to know. This modularization has had positive effects, in that scientists are able to have deeper, more engaging conversations without having to appease a recommendation algorithm hungry for superficial engagement-primed posts, or edit into oblivion to reach a tiny character limit. Nuance and attention to detail are the lifeblood of good science, and I'm sure many of us have missed it in online spaces.  The promise of search on Mastodon beyond hastags and specific profile urls may alleviate this to some extent, albeit not without concerns about opt-in/out rights for users to shield themselves from the kind of targeted harassment for which Twitter and Facebook are so notorious. On a rare point of optimism for me, I choose to be confident that the open and user-focused principles underpinning the Fediverse and Mastodon's existences will reach solution(s) that make everyone reasonably happy.

This future does require some work to build, though. As would-be science communicators in a setting where no algorithm is throwing what we have to say in other people's faces, we need to reach out and form networks with each other, and with a non-scientist audience, organically. I don't claim to know the best ways to do that, but I'm hoping Network Science has some insights. More on that to come. 

<!--- Put this in a different post?

### On recentralization, or, don't feed the data parasites

Mastodon has been abuzz with concerns about another problem: the perceived encroachment of the same corporations behind the platforms so many left behind into the Fediverse. Not long after Elon's takeover, Jack Dorsey launched "BlueSky," a comparatively bare bones, invite-only platform based largely on Twitter source. It currently does not federate, but it seems likely that will happen in the future. Of seemingly more urgent concern is the news that "Meta," the parent company of Facebook conveniently rebranded to distance itself from Cambridge Analytica and the sentiment analysis feedback loop-driven organization of several fascist coup attempts around the world, is planning to launch its own social network based on Mastodon's source, with the apparent intention of federating. 
--->